version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
  - package-ecosystem: github-actions
    directory: /
    exclude-paths:
      - .github/workflows/release.yml
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
